"""Add color field to collections

Revision ID: 95d51dcae914
Revises: c3d5816e59a1
Create Date: 2025-06-12 15:44:46.489909

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '95d51dcae914'
down_revision = 'c3d5816e59a1'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Create the enum type first
    collection_color_enum = sa.Enum(
        'BLUE', 'GREEN', 'PURPLE', 'ORANGE', 'RED', 'PINK', 
        'TEAL', 'INDIGO', 'YELLOW', 'EMERALD', 'ROSE', 'CYAN', 
        name='collectioncolor'
    )
    collection_color_enum.create(op.get_bind())
    
    # Add the column as nullable
    op.add_column('collections', sa.Column('color', collection_color_enum, nullable=True))
    
    # Set a default color for existing collections
    op.execute("UPDATE collections SET color = 'BLUE' WHERE color IS NULL")
    
    # Make the column non-nullable
    op.alter_column('collections', 'color', nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('collections', 'color')
    # Drop the enum type if no other tables use it
    op.execute("DROP TYPE IF EXISTS collectioncolor")
    # ### end Alembic commands ### 