"""Add privacy controls and share link system

Revision ID: a38b6bb1ba7b
Revises: cfacc5a29786
Create Date: 2025-05-27 10:51:00.418620

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a38b6bb1ba7b'
down_revision = 'cfacc5a29786'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ### 