"""Update user model for Supabase integration

Revision ID: c3d5816e59a1
Revises: 87a9043184d6
Create Date: 2025-06-09 10:56:55.725238

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c3d5816e59a1'
down_revision = '87a9043184d6'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Add new columns for Supabase integration
    op.add_column('users', sa.Column('provider', sa.String(length=20), nullable=False))
    op.add_column('users', sa.Column('email', sa.String(length=255), nullable=True))
    
    # Drop old OAuth columns and indexes (no existing users to worry about)
    op.drop_index(op.f('ix_users_apple_id'), table_name='users')
    op.drop_index(op.f('ix_users_google_id'), table_name='users')
    op.drop_column('users', 'google_id')
    op.drop_column('users', 'apple_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('apple_id', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('google_id', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.create_index(op.f('ix_users_google_id'), 'users', ['google_id'], unique=True)
    op.create_index(op.f('ix_users_apple_id'), 'users', ['apple_id'], unique=True)
    op.drop_column('users', 'email')
    op.drop_column('users', 'provider')
    # ### end Alembic commands ### 